version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "uv"
    directory: "/scripts"
    schedule:
      interval: "daily"
