name: 📖 Content issue
description: Report an issue with the content
body:
  - type: markdown
    attributes:
      value: |
        Use this form to report an issue with the content.

        When contributing, make sure to follow Contributing guidelines and Code of Conduct.
        Thank you for your contribution!

  - type: checkboxes
    attributes:
      label: Existing issues
      description: Is there an existing issue for this? Search open and closed issues to avoid duplicates.
      options:
        - label: I have searched the existing issues.
          required: true

  - type: input
    attributes:
      label: Affected document
      description: Name or paste a link to the document that contains an issue.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue description
      description: Explain what is unclear or confusing in the given document.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Attachments
      description: Include screenshots or links if applicable.
    validations:
      required: false
