name: check code snippets

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-code-snippets:
    name: check-code-snippets
    runs-on:
      - ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: scripts/uv.lock
      - name: Validate code snippets
        env:
          GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}
        run: |
          uv run --project scripts --locked ./scripts/check_code_snippets.py .
